import '@/styles/globals.css';
import Head from 'next/head';
import type { AppProps } from 'next/app';
import ErrorBoundary from '../../components/error-boundary/error-boundary';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <ErrorBoundary>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
        <title>Art miseum</title>
      </Head>
      <Component {...pageProps} />
    </ErrorBoundary>
  );
}
